version: "3.1"

services:
  db:
    image: "postgres:11"
    restart: always
    env_file: .env
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - 3022:3011
    depends_on:
      - db
